### ISSUE TITLE
A few suggestions: 1) Remove Yieldly-specific methods (only use ASA methods) 2) Rename "Deposit" to "Stake"

### ISSUE THREAD

**Issue by majestique** [geoffodonnell/dotnet-yieldly-sdk#1]
Suggestion 1 would make fewer lines of code, and more flexibility. Suggestion 2 would make it easier to understand that "Deposit" means Stake or maybe a comment that confirms that functionality.

**Comment by geoffodonnell** [comment]
Helpful suggestion, but I think leaving the V1 API alone is the right thing to do.
